/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.CreateAssetAction');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CreateAssetAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CreateAssetAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.CreateAssetAction.displayName = 'proto.CreateAssetAction';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CreateAssetAction.prototype.toObject = function(opt_includeInstance) {
  return proto.CreateAssetAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CreateAssetAction} msg The msg instance to transform.
 * @return {!Object}
 */
proto.CreateAssetAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    rfid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    sizeL: jspb.Message.getFieldWithDefault(msg, 2, 0),
    sizeR: jspb.Message.getFieldWithDefault(msg, 3, 0),
    sku: jspb.Message.getFieldWithDefault(msg, 4, ""),
    longitude: jspb.Message.getFieldWithDefault(msg, 5, 0),
    latitude: jspb.Message.getFieldWithDefault(msg, 6, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CreateAssetAction}
 */
proto.CreateAssetAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CreateAssetAction;
  return proto.CreateAssetAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CreateAssetAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CreateAssetAction}
 */
proto.CreateAssetAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRfid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSizeL(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSizeR(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSku(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setLongitude(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setLatitude(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CreateAssetAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CreateAssetAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CreateAssetAction} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.CreateAssetAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRfid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSizeL();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getSizeR();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getSku();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getLongitude();
  if (f !== 0) {
    writer.writeSint64(
      5,
      f
    );
  }
  f = message.getLatitude();
  if (f !== 0) {
    writer.writeSint64(
      6,
      f
    );
  }
};


/**
 * optional string rfid = 1;
 * @return {string}
 */
proto.CreateAssetAction.prototype.getRfid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.CreateAssetAction.prototype.setRfid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional uint32 size_l = 2;
 * @return {number}
 */
proto.CreateAssetAction.prototype.getSizeL = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.CreateAssetAction.prototype.setSizeL = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional uint32 size_r = 3;
 * @return {number}
 */
proto.CreateAssetAction.prototype.getSizeR = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.CreateAssetAction.prototype.setSizeR = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string sku = 4;
 * @return {string}
 */
proto.CreateAssetAction.prototype.getSku = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.CreateAssetAction.prototype.setSku = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional sint64 longitude = 5;
 * @return {number}
 */
proto.CreateAssetAction.prototype.getLongitude = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.CreateAssetAction.prototype.setLongitude = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional sint64 latitude = 6;
 * @return {number}
 */
proto.CreateAssetAction.prototype.getLatitude = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.CreateAssetAction.prototype.setLatitude = function(value) {
  jspb.Message.setField(this, 6, value);
};


