/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

goog.provide('proto.History');
goog.provide('proto.History.Reporter');

goog.require('jspb.Message');
goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');


/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.History = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.History.repeatedFields_, null);
};
goog.inherits(proto.History, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.History.displayName = 'proto.History';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.History.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.History.prototype.toObject = function(opt_includeInstance) {
  return proto.History.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.History} msg The msg instance to transform.
 * @return {!Object}
 */
proto.History.toObject = function(includeInstance, msg) {
  var f, obj = {
    rfid: jspb.Message.getFieldWithDefault(msg, 1, 0),
    currTouchpointIndex: jspb.Message.getFieldWithDefault(msg, 2, 0),
    hasWrapped: jspb.Message.getFieldWithDefault(msg, 3, false),
    reporterListList: jspb.Message.toObjectList(msg.getReporterListList(),
    proto.History.Reporter.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.History}
 */
proto.History.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.History;
  return proto.History.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.History} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.History}
 */
proto.History.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRfid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCurrTouchpointIndex(value);
      break;
    case 3:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setHasWrapped(value);
      break;
    case 4:
      var value = new proto.History.Reporter;
      reader.readMessage(value,proto.History.Reporter.deserializeBinaryFromReader);
      msg.addReporterList(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.History.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.History.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.History} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.History.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRfid();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getCurrTouchpointIndex();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getHasWrapped();
  if (f) {
    writer.writeBool(
      3,
      f
    );
  }
  f = message.getReporterListList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.History.Reporter.serializeBinaryToWriter
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.History.Reporter = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.History.Reporter, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.History.Reporter.displayName = 'proto.History.Reporter';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.History.Reporter.prototype.toObject = function(opt_includeInstance) {
  return proto.History.Reporter.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.History.Reporter} msg The msg instance to transform.
 * @return {!Object}
 */
proto.History.Reporter.toObject = function(includeInstance, msg) {
  var f, obj = {
    publicKey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    authorizationLevel: jspb.Message.getFieldWithDefault(msg, 2, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.History.Reporter}
 */
proto.History.Reporter.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.History.Reporter;
  return proto.History.Reporter.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.History.Reporter} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.History.Reporter}
 */
proto.History.Reporter.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPublicKey(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAuthorizationLevel(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.History.Reporter.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.History.Reporter.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.History.Reporter} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.History.Reporter.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPublicKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAuthorizationLevel();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
};


/**
 * optional string public_key = 1;
 * @return {string}
 */
proto.History.Reporter.prototype.getPublicKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.History.Reporter.prototype.setPublicKey = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional uint32 authorization_level = 2;
 * @return {number}
 */
proto.History.Reporter.prototype.getAuthorizationLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.History.Reporter.prototype.setAuthorizationLevel = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional uint32 rfid = 1;
 * @return {number}
 */
proto.History.prototype.getRfid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.History.prototype.setRfid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional uint32 curr_touchpoint_index = 2;
 * @return {number}
 */
proto.History.prototype.getCurrTouchpointIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.History.prototype.setCurrTouchpointIndex = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional bool has_wrapped = 3;
 * Note that Boolean fields may be set to 0/1 when serialized from a Java server.
 * You should avoid comparisons like {@code val === true/false} in those cases.
 * @return {boolean}
 */
proto.History.prototype.getHasWrapped = function() {
  return /** @type {boolean} */ (jspb.Message.getFieldWithDefault(this, 3, false));
};


/** @param {boolean} value */
proto.History.prototype.setHasWrapped = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * repeated Reporter reporter_list = 4;
 * If you change this array by adding, removing or replacing elements, or if you
 * replace the array itself, then you must call the setter to update it.
 * @return {!Array.<!proto.History.Reporter>}
 */
proto.History.prototype.getReporterListList = function() {
  return /** @type{!Array.<!proto.History.Reporter>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.History.Reporter, 4));
};


/** @param {!Array.<!proto.History.Reporter>} value */
proto.History.prototype.setReporterListList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.History.Reporter=} opt_value
 * @param {number=} opt_index
 * @return {!proto.History.Reporter}
 */
proto.History.prototype.addReporterList = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.History.Reporter, opt_index);
};


proto.History.prototype.clearReporterListList = function() {
  this.setReporterListList([]);
};


