# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: history.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='history.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rhistory.proto\"\xb2\x01\n\x07History\x12\x0c\n\x04rfid\x18\x01 \x01(\r\x12\x1d\n\x15\x63urr_touchpoint_index\x18\x02 \x01(\r\x12\x13\n\x0bhas_wrapped\x18\x03 \x01(\x08\x12(\n\rreporter_list\x18\x04 \x03(\x0b\x32\x11.History.Reporter\x1a;\n\x08Reporter\x12\x12\n\npublic_key\x18\x01 \x01(\t\x12\x1b\n\x13\x61uthorization_level\x18\x02 \x01(\r\"\\\n\nTouchPoint\x12\x11\n\tlongitude\x18\x01 \x01(\x12\x12\x10\n\x08latitude\x18\x02 \x01(\x12\x12\x11\n\ttimestamp\x18\x03 \x01(\x04\x12\x16\n\x0ereporter_index\x18\x04 \x01(\r\"-\n\x10HistoryContainer\x12\x19\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x08.History\"3\n\x13TouchPointContainer\x12\x1c\n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0b.TouchPointb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_HISTORY_REPORTER = _descriptor.Descriptor(
  name='Reporter',
  full_name='History.Reporter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='public_key', full_name='History.Reporter.public_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='authorization_level', full_name='History.Reporter.authorization_level', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=196,
)

_HISTORY = _descriptor.Descriptor(
  name='History',
  full_name='History',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rfid', full_name='History.rfid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='curr_touchpoint_index', full_name='History.curr_touchpoint_index', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='has_wrapped', full_name='History.has_wrapped', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reporter_list', full_name='History.reporter_list', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_HISTORY_REPORTER, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=196,
)


_TOUCHPOINT = _descriptor.Descriptor(
  name='TouchPoint',
  full_name='TouchPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='longitude', full_name='TouchPoint.longitude', index=0,
      number=1, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='TouchPoint.latitude', index=1,
      number=2, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='TouchPoint.timestamp', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reporter_index', full_name='TouchPoint.reporter_index', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=198,
  serialized_end=290,
)


_HISTORYCONTAINER = _descriptor.Descriptor(
  name='HistoryContainer',
  full_name='HistoryContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='HistoryContainer.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=292,
  serialized_end=337,
)


_TOUCHPOINTCONTAINER = _descriptor.Descriptor(
  name='TouchPointContainer',
  full_name='TouchPointContainer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entries', full_name='TouchPointContainer.entries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=339,
  serialized_end=390,
)

_HISTORY_REPORTER.containing_type = _HISTORY
_HISTORY.fields_by_name['reporter_list'].message_type = _HISTORY_REPORTER
_HISTORYCONTAINER.fields_by_name['entries'].message_type = _HISTORY
_TOUCHPOINTCONTAINER.fields_by_name['entries'].message_type = _TOUCHPOINT
DESCRIPTOR.message_types_by_name['History'] = _HISTORY
DESCRIPTOR.message_types_by_name['TouchPoint'] = _TOUCHPOINT
DESCRIPTOR.message_types_by_name['HistoryContainer'] = _HISTORYCONTAINER
DESCRIPTOR.message_types_by_name['TouchPointContainer'] = _TOUCHPOINTCONTAINER

History = _reflection.GeneratedProtocolMessageType('History', (_message.Message,), dict(

  Reporter = _reflection.GeneratedProtocolMessageType('Reporter', (_message.Message,), dict(
    DESCRIPTOR = _HISTORY_REPORTER,
    __module__ = 'history_pb2'
    # @@protoc_insertion_point(class_scope:History.Reporter)
    ))
  ,
  DESCRIPTOR = _HISTORY,
  __module__ = 'history_pb2'
  # @@protoc_insertion_point(class_scope:History)
  ))
_sym_db.RegisterMessage(History)
_sym_db.RegisterMessage(History.Reporter)

TouchPoint = _reflection.GeneratedProtocolMessageType('TouchPoint', (_message.Message,), dict(
  DESCRIPTOR = _TOUCHPOINT,
  __module__ = 'history_pb2'
  # @@protoc_insertion_point(class_scope:TouchPoint)
  ))
_sym_db.RegisterMessage(TouchPoint)

HistoryContainer = _reflection.GeneratedProtocolMessageType('HistoryContainer', (_message.Message,), dict(
  DESCRIPTOR = _HISTORYCONTAINER,
  __module__ = 'history_pb2'
  # @@protoc_insertion_point(class_scope:HistoryContainer)
  ))
_sym_db.RegisterMessage(HistoryContainer)

TouchPointContainer = _reflection.GeneratedProtocolMessageType('TouchPointContainer', (_message.Message,), dict(
  DESCRIPTOR = _TOUCHPOINTCONTAINER,
  __module__ = 'history_pb2'
  # @@protoc_insertion_point(class_scope:TouchPointContainer)
  ))
_sym_db.RegisterMessage(TouchPointContainer)


# @@protoc_insertion_point(module_scope)
