# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\rpayload.proto\"\xbc\x01\n\x07Payload\x12\x1f\n\x06\x61\x63tion\x18\x01 \x01(\x0e\x32\x0f.Payload.Action\x12\x11\n\ttimestamp\x18\x02 \x01(\x04\x12(\n\x0c\x63reate_asset\x18\x03 \x01(\x0b\x32\x12.CreateAssetAction\x12&\n\x0btouch_asset\x18\x04 \x01(\x0b\x32\x11.TouchAssetAction\"+\n\x06\x41\x63tion\x12\x10\n\x0c\x43REATE_ASSET\x10\x00\x12\x0f\n\x0bTOUCH_ASSET\x10\x01\"s\n\x11\x43reateAssetAction\x12\x0c\n\x04rfid\x18\x01 \x01(\t\x12\x0e\n\x06size_l\x18\x02 \x01(\r\x12\x0e\n\x06size_r\x18\x03 \x01(\r\x12\x0b\n\x03sku\x18\x04 \x01(\t\x12\x11\n\tlongitude\x18\x05 \x01(\x12\x12\x10\n\x08latitude\x18\x06 \x01(\x12\"E\n\x10TouchAssetAction\x12\x0c\n\x04rfid\x18\x01 \x01(\t\x12\x11\n\tlongitude\x18\x02 \x01(\x12\x12\x10\n\x08latitude\x18\x03 \x01(\x12\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_PAYLOAD_ACTION = _descriptor.EnumDescriptor(
  name='Action',
  full_name='Payload.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CREATE_ASSET', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TOUCH_ASSET', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=163,
  serialized_end=206,
)
_sym_db.RegisterEnumDescriptor(_PAYLOAD_ACTION)


_PAYLOAD = _descriptor.Descriptor(
  name='Payload',
  full_name='Payload',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='Payload.action', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='Payload.timestamp', index=1,
      number=2, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='create_asset', full_name='Payload.create_asset', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='touch_asset', full_name='Payload.touch_asset', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PAYLOAD_ACTION,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=206,
)


_CREATEASSETACTION = _descriptor.Descriptor(
  name='CreateAssetAction',
  full_name='CreateAssetAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rfid', full_name='CreateAssetAction.rfid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size_l', full_name='CreateAssetAction.size_l', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='size_r', full_name='CreateAssetAction.size_r', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sku', full_name='CreateAssetAction.sku', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='CreateAssetAction.longitude', index=4,
      number=5, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='CreateAssetAction.latitude', index=5,
      number=6, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=208,
  serialized_end=323,
)


_TOUCHASSETACTION = _descriptor.Descriptor(
  name='TouchAssetAction',
  full_name='TouchAssetAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rfid', full_name='TouchAssetAction.rfid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='longitude', full_name='TouchAssetAction.longitude', index=1,
      number=2, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='latitude', full_name='TouchAssetAction.latitude', index=2,
      number=3, type=18, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=394,
)

_PAYLOAD.fields_by_name['action'].enum_type = _PAYLOAD_ACTION
_PAYLOAD.fields_by_name['create_asset'].message_type = _CREATEASSETACTION
_PAYLOAD.fields_by_name['touch_asset'].message_type = _TOUCHASSETACTION
_PAYLOAD_ACTION.containing_type = _PAYLOAD
DESCRIPTOR.message_types_by_name['Payload'] = _PAYLOAD
DESCRIPTOR.message_types_by_name['CreateAssetAction'] = _CREATEASSETACTION
DESCRIPTOR.message_types_by_name['TouchAssetAction'] = _TOUCHASSETACTION

Payload = _reflection.GeneratedProtocolMessageType('Payload', (_message.Message,), dict(
  DESCRIPTOR = _PAYLOAD,
  __module__ = 'payload_pb2'
  # @@protoc_insertion_point(class_scope:Payload)
  ))
_sym_db.RegisterMessage(Payload)

CreateAssetAction = _reflection.GeneratedProtocolMessageType('CreateAssetAction', (_message.Message,), dict(
  DESCRIPTOR = _CREATEASSETACTION,
  __module__ = 'payload_pb2'
  # @@protoc_insertion_point(class_scope:CreateAssetAction)
  ))
_sym_db.RegisterMessage(CreateAssetAction)

TouchAssetAction = _reflection.GeneratedProtocolMessageType('TouchAssetAction', (_message.Message,), dict(
  DESCRIPTOR = _TOUCHASSETACTION,
  __module__ = 'payload_pb2'
  # @@protoc_insertion_point(class_scope:TouchAssetAction)
  ))
_sym_db.RegisterMessage(TouchAssetAction)


# @@protoc_insertion_point(module_scope)
