/* Team B is comprised of the following individuals:
    - Roberto Avila
    - Andrew Burnett
    - Jeff De La Mare
    - Nick Nation
    - Phillip Nguyen
    - Anthony Tran
    - Joseph Venetucci

[This program is licensed under the "MIT License"]
Please see the file LICENSE.md in the 
source distribution of this software for license terms.

This software also makes use of Hyperledger Sawtooth which is
licensed under Apache 2.0. A copy of it's license and copyright
are contained in sawtooth-license.md and sawtooth-copyright.md */


/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.CreateAgentAction', null, global);
goog.exportSymbol('proto.CreateAssetAction', null, global);
goog.exportSymbol('proto.LockAssetAction', null, global);
goog.exportSymbol('proto.Payload', null, global);
goog.exportSymbol('proto.Payload.Action', null, global);
goog.exportSymbol('proto.TouchAssetAction', null, global);
goog.exportSymbol('proto.UnlockAssetAction', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Payload = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Payload, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.Payload.displayName = 'proto.Payload';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Payload.prototype.toObject = function(opt_includeInstance) {
  return proto.Payload.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Payload} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Payload.toObject = function(includeInstance, msg) {
  var f, obj = {
    action: jspb.Message.getFieldWithDefault(msg, 1, 0),
    timestamp: jspb.Message.getFieldWithDefault(msg, 2, 0),
    createAsset: (f = msg.getCreateAsset()) && proto.CreateAssetAction.toObject(includeInstance, f),
    createAgent: (f = msg.getCreateAgent()) && proto.CreateAgentAction.toObject(includeInstance, f),
    touchAsset: (f = msg.getTouchAsset()) && proto.TouchAssetAction.toObject(includeInstance, f),
    lockAsset: (f = msg.getLockAsset()) && proto.LockAssetAction.toObject(includeInstance, f),
    unlockAsset: (f = msg.getUnlockAsset()) && proto.UnlockAssetAction.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Payload}
 */
proto.Payload.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Payload;
  return proto.Payload.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Payload} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Payload}
 */
proto.Payload.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.Payload.Action} */ (reader.readEnum());
      msg.setAction(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setTimestamp(value);
      break;
    case 3:
      var value = new proto.CreateAssetAction;
      reader.readMessage(value,proto.CreateAssetAction.deserializeBinaryFromReader);
      msg.setCreateAsset(value);
      break;
    case 4:
      var value = new proto.CreateAgentAction;
      reader.readMessage(value,proto.CreateAgentAction.deserializeBinaryFromReader);
      msg.setCreateAgent(value);
      break;
    case 5:
      var value = new proto.TouchAssetAction;
      reader.readMessage(value,proto.TouchAssetAction.deserializeBinaryFromReader);
      msg.setTouchAsset(value);
      break;
    case 6:
      var value = new proto.LockAssetAction;
      reader.readMessage(value,proto.LockAssetAction.deserializeBinaryFromReader);
      msg.setLockAsset(value);
      break;
    case 7:
      var value = new proto.UnlockAssetAction;
      reader.readMessage(value,proto.UnlockAssetAction.deserializeBinaryFromReader);
      msg.setUnlockAsset(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Payload.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Payload.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Payload} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Payload.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAction();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getTimestamp();
  if (f !== 0) {
    writer.writeUint64(
      2,
      f
    );
  }
  f = message.getCreateAsset();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      proto.CreateAssetAction.serializeBinaryToWriter
    );
  }
  f = message.getCreateAgent();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.CreateAgentAction.serializeBinaryToWriter
    );
  }
  f = message.getTouchAsset();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.TouchAssetAction.serializeBinaryToWriter
    );
  }
  f = message.getLockAsset();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.LockAssetAction.serializeBinaryToWriter
    );
  }
  f = message.getUnlockAsset();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.UnlockAssetAction.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.Payload.Action = {
  CREATE_ASSET: 0,
  CREATE_AGENT: 1,
  TOUCH_ASSET: 2,
  LOCK_ASSET: 3,
  UNLOCK_ASSET: 4
};

/**
 * optional Action action = 1;
 * @return {!proto.Payload.Action}
 */
proto.Payload.prototype.getAction = function() {
  return /** @type {!proto.Payload.Action} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.Payload.Action} value */
proto.Payload.prototype.setAction = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional uint64 timestamp = 2;
 * @return {number}
 */
proto.Payload.prototype.getTimestamp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.Payload.prototype.setTimestamp = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional CreateAssetAction create_asset = 3;
 * @return {?proto.CreateAssetAction}
 */
proto.Payload.prototype.getCreateAsset = function() {
  return /** @type{?proto.CreateAssetAction} */ (
    jspb.Message.getWrapperField(this, proto.CreateAssetAction, 3));
};


/** @param {?proto.CreateAssetAction|undefined} value */
proto.Payload.prototype.setCreateAsset = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.Payload.prototype.clearCreateAsset = function() {
  this.setCreateAsset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Payload.prototype.hasCreateAsset = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional CreateAgentAction create_agent = 4;
 * @return {?proto.CreateAgentAction}
 */
proto.Payload.prototype.getCreateAgent = function() {
  return /** @type{?proto.CreateAgentAction} */ (
    jspb.Message.getWrapperField(this, proto.CreateAgentAction, 4));
};


/** @param {?proto.CreateAgentAction|undefined} value */
proto.Payload.prototype.setCreateAgent = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.Payload.prototype.clearCreateAgent = function() {
  this.setCreateAgent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Payload.prototype.hasCreateAgent = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional TouchAssetAction touch_asset = 5;
 * @return {?proto.TouchAssetAction}
 */
proto.Payload.prototype.getTouchAsset = function() {
  return /** @type{?proto.TouchAssetAction} */ (
    jspb.Message.getWrapperField(this, proto.TouchAssetAction, 5));
};


/** @param {?proto.TouchAssetAction|undefined} value */
proto.Payload.prototype.setTouchAsset = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.Payload.prototype.clearTouchAsset = function() {
  this.setTouchAsset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Payload.prototype.hasTouchAsset = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional LockAssetAction lock_asset = 6;
 * @return {?proto.LockAssetAction}
 */
proto.Payload.prototype.getLockAsset = function() {
  return /** @type{?proto.LockAssetAction} */ (
    jspb.Message.getWrapperField(this, proto.LockAssetAction, 6));
};


/** @param {?proto.LockAssetAction|undefined} value */
proto.Payload.prototype.setLockAsset = function(value) {
  jspb.Message.setWrapperField(this, 6, value);
};


proto.Payload.prototype.clearLockAsset = function() {
  this.setLockAsset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Payload.prototype.hasLockAsset = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional UnlockAssetAction unlock_asset = 7;
 * @return {?proto.UnlockAssetAction}
 */
proto.Payload.prototype.getUnlockAsset = function() {
  return /** @type{?proto.UnlockAssetAction} */ (
    jspb.Message.getWrapperField(this, proto.UnlockAssetAction, 7));
};


/** @param {?proto.UnlockAssetAction|undefined} value */
proto.Payload.prototype.setUnlockAsset = function(value) {
  jspb.Message.setWrapperField(this, 7, value);
};


proto.Payload.prototype.clearUnlockAsset = function() {
  this.setUnlockAsset(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.Payload.prototype.hasUnlockAsset = function() {
  return jspb.Message.getField(this, 7) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CreateAssetAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CreateAssetAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.CreateAssetAction.displayName = 'proto.CreateAssetAction';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CreateAssetAction.prototype.toObject = function(opt_includeInstance) {
  return proto.CreateAssetAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CreateAssetAction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CreateAssetAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    rfid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    size: jspb.Message.getFieldWithDefault(msg, 2, ""),
    sku: jspb.Message.getFieldWithDefault(msg, 3, ""),
    longitude: jspb.Message.getFieldWithDefault(msg, 4, 0),
    latitude: jspb.Message.getFieldWithDefault(msg, 5, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CreateAssetAction}
 */
proto.CreateAssetAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CreateAssetAction;
  return proto.CreateAssetAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CreateAssetAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CreateAssetAction}
 */
proto.CreateAssetAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRfid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setSize(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setSku(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setLongitude(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setLatitude(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CreateAssetAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CreateAssetAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CreateAssetAction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CreateAssetAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRfid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getSize();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getSku();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLongitude();
  if (f !== 0) {
    writer.writeSint64(
      4,
      f
    );
  }
  f = message.getLatitude();
  if (f !== 0) {
    writer.writeSint64(
      5,
      f
    );
  }
};


/**
 * optional string rfid = 1;
 * @return {string}
 */
proto.CreateAssetAction.prototype.getRfid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.CreateAssetAction.prototype.setRfid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string size = 2;
 * @return {string}
 */
proto.CreateAssetAction.prototype.getSize = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.CreateAssetAction.prototype.setSize = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string sku = 3;
 * @return {string}
 */
proto.CreateAssetAction.prototype.getSku = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.CreateAssetAction.prototype.setSku = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional sint64 longitude = 4;
 * @return {number}
 */
proto.CreateAssetAction.prototype.getLongitude = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.CreateAssetAction.prototype.setLongitude = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional sint64 latitude = 5;
 * @return {number}
 */
proto.CreateAssetAction.prototype.getLatitude = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.CreateAssetAction.prototype.setLatitude = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.CreateAgentAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.CreateAgentAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.CreateAgentAction.displayName = 'proto.CreateAgentAction';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.CreateAgentAction.prototype.toObject = function(opt_includeInstance) {
  return proto.CreateAgentAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.CreateAgentAction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CreateAgentAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    publicKey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    role: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.CreateAgentAction}
 */
proto.CreateAgentAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.CreateAgentAction;
  return proto.CreateAgentAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.CreateAgentAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.CreateAgentAction}
 */
proto.CreateAgentAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPublicKey(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRole(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.CreateAgentAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.CreateAgentAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.CreateAgentAction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.CreateAgentAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPublicKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getRole();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional string public_key = 1;
 * @return {string}
 */
proto.CreateAgentAction.prototype.getPublicKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.CreateAgentAction.prototype.setPublicKey = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.CreateAgentAction.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.CreateAgentAction.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int32 role = 3;
 * @return {number}
 */
proto.CreateAgentAction.prototype.getRole = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.CreateAgentAction.prototype.setRole = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.TouchAssetAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.TouchAssetAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.TouchAssetAction.displayName = 'proto.TouchAssetAction';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.TouchAssetAction.prototype.toObject = function(opt_includeInstance) {
  return proto.TouchAssetAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.TouchAssetAction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TouchAssetAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    rfid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    longitude: jspb.Message.getFieldWithDefault(msg, 2, 0),
    latitude: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.TouchAssetAction}
 */
proto.TouchAssetAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.TouchAssetAction;
  return proto.TouchAssetAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.TouchAssetAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.TouchAssetAction}
 */
proto.TouchAssetAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRfid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setLongitude(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readSint64());
      msg.setLatitude(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.TouchAssetAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.TouchAssetAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.TouchAssetAction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.TouchAssetAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRfid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLongitude();
  if (f !== 0) {
    writer.writeSint64(
      2,
      f
    );
  }
  f = message.getLatitude();
  if (f !== 0) {
    writer.writeSint64(
      3,
      f
    );
  }
};


/**
 * optional string rfid = 1;
 * @return {string}
 */
proto.TouchAssetAction.prototype.getRfid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.TouchAssetAction.prototype.setRfid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional sint64 longitude = 2;
 * @return {number}
 */
proto.TouchAssetAction.prototype.getLongitude = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.TouchAssetAction.prototype.setLongitude = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional sint64 latitude = 3;
 * @return {number}
 */
proto.TouchAssetAction.prototype.getLatitude = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.TouchAssetAction.prototype.setLatitude = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.LockAssetAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.LockAssetAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.LockAssetAction.displayName = 'proto.LockAssetAction';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.LockAssetAction.prototype.toObject = function(opt_includeInstance) {
  return proto.LockAssetAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.LockAssetAction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LockAssetAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    rfid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.LockAssetAction}
 */
proto.LockAssetAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.LockAssetAction;
  return proto.LockAssetAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.LockAssetAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.LockAssetAction}
 */
proto.LockAssetAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRfid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.LockAssetAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.LockAssetAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.LockAssetAction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.LockAssetAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRfid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string rfid = 1;
 * @return {string}
 */
proto.LockAssetAction.prototype.getRfid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.LockAssetAction.prototype.setRfid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.UnlockAssetAction = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.UnlockAssetAction, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.UnlockAssetAction.displayName = 'proto.UnlockAssetAction';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.UnlockAssetAction.prototype.toObject = function(opt_includeInstance) {
  return proto.UnlockAssetAction.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.UnlockAssetAction} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UnlockAssetAction.toObject = function(includeInstance, msg) {
  var f, obj = {
    rfid: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.UnlockAssetAction}
 */
proto.UnlockAssetAction.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.UnlockAssetAction;
  return proto.UnlockAssetAction.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.UnlockAssetAction} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.UnlockAssetAction}
 */
proto.UnlockAssetAction.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setRfid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.UnlockAssetAction.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.UnlockAssetAction.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.UnlockAssetAction} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.UnlockAssetAction.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getRfid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string rfid = 1;
 * @return {string}
 */
proto.UnlockAssetAction.prototype.getRfid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.UnlockAssetAction.prototype.setRfid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


goog.object.extend(exports, proto);
